#ifndef ROBOT_CONTROL_GLOBAL_H
#define ROBOT_CONTROL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ROBOT_CONTROL_LIBRARY)
#  define ROBOT_CONTROLSHARED_EXPORT Q_DECL_EXPORT
#else
#  define ROBOT_CONTROLSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // ROBOT_CONTROL_GLOBAL_H
